apiVersion: v1
kind: Pod
metadata:
  name: cfi-books-pod
  labels:
    app: cfi-books
spec:
  containers:
  - name: cfi-books
    image: gsantoro/cfi-books:latest
    command: ["gunicorn"]
    args: ["-b 127.0.0.1:8080", "app:app"]
  - name: cfi-books-gateway
    image: gsantoro/cfi-books-gateway:latest
    ports:
      - containerPort: 80
        name: http
        protocol: TCP
