version: '2.0'
services:
  app:
    build: ..
    container_name: cfi-flask
  nginx:
    image: nginx:1.17.9-alpine
    container_name: cfi-nginx
    links:
      - app
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
