version: '3.7'
services:
  app:
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: cfi-flask
  nginx:
    build:
      context: .
      dockerfile: nginx.Dockerfile
    container_name: cfi-nginx
    links:
      - app
    ports:
      - "8080:80"
